### PR TITLE
disable duration extraction

### PR DESCRIPTION
**Pull request by bcomnes**
@ungoldman does this speed up scanning for you? Or is it still slow.

### CODE REVIEW

**Comment by ungoldman** [comment]
I see the duration showing up for every track after a scan so not sure if setting duration to false is working as expected. Also I think the duration slow down is less serious than the latest metadata lib failing on my itunes directory.

Here's the error for that:

```
(node:7534) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'no' of undefined
(node:7534) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ungoldman** [comment]
Only reference to a `.no` prop I can find is in `main/lib/audio-library/sort.js`, so I'm guessing in some version of `music-metadata` they removed the `no` prop from metadata where track or disk data was missing.

**Comment by bcomnes** [comment]
Crap, sorry about that.  We should fix that bug now, but the scanning / data retrieval process needs an overhaul.  

I've had an idea to get the scan speed down to folder walker speeds, and kick off a background tasks to scan metadata and send it to the UI in chunks as it becomes available.  Would require some medium sized refactoring.

**Comment by ungoldman** [comment]
Going to merge this as I see no problems with it.

**Pull request merged**
