### PR TITLE
Implement Button groups

### PR DESCRIPTION
**Pull request by bcomnes**
Closes https://github.com/hypermodules/hyperamp/issues/69

I also removed the * selectors.  Weirdly, I personally prefer applying border-box selectively. You cool with that @ungoldman ?

### CODE REVIEW

**Comment by bcomnes** [comment]
screen shot 2016-12-17 at 6 02 03 pm

**Comment by ungoldman** [comment]
Looks good! Does the button work by itself (outside button group) without `display: inline-flex`? I found I needed it to keep it inline while vertically centering SVG icons.

I definitely added the `*` group on purpose, but if you want it that way I can live it with.

**Comment by bcomnes** [comment]
I think so.  

https://github.com/hypermodules/hyperamp/blob/master/renderer/views/components/toolbar.js#L26 Would be an example of this right?  I decided I didn't like the inline with the buttons because I was getting weird inline spacing between buttons that didn't reflect in the box model hover indicators.  So I just treat them like block elements and flex-row the parent.  Even though buttons then default to stacking, flexing the parent into a row makes them row up, and behave super predictably at that point.

Eg, this is what buttons look like in a `display: flex` row w/o the btnGroup class:

screen shot 2016-12-17 at 6 42 38 pm

**Comment by bcomnes** [comment]
I'll put the * selector back then.

**Comment by ungoldman** [comment]
I guess that makes sense. Just used to `button` being an inline element by default.

**Comment by ungoldman** [comment]
No it's fine, we don't need `border-box` everywhere and html already covers cursor and the other one. I'm just being grumpy.

**Comment by bcomnes** [comment]
The best reason I can give to this preference is that * selecting border-box everywhere applies it in many places that don't get affected by it, and it makes it less clear where its actually needed in the dom tree.

**Comment by ungoldman** [comment]
I think I just inherited the practice from some article I read a while back. Something like this but different.

https://www.paulirish.com/2012/box-sizing-border-box-ftw/

I'm fine with the way you've got it.

**Comment by ungoldman** [comment]
Cool with merging this when you're ready btw

**Comment by ungoldman** [comment]
I disabled merge commits cause squash or rebase are more baller

**Comment by ungoldman** [comment]
Sometimes wish issue comments were real time chat format

**Comment by bcomnes** [comment]
I need a `...` typing bubble.

**Pull request merged**
