### PR TITLE
experimental alternate layout & style

### PR DESCRIPTION
**Pull request by ungoldman**
still very WIP. I think it's looking pretty good though

screen shot 2017-04-26 at 9 53 30 pm

### CODE REVIEW

**Comment by bcomnes** [comment]
Oh wow that looks great!

**Comment by bcomnes** [comment]
Want me to merge https://github.com/hypermodules/hyperamp/pull/154 so there is less worry of conflicts?

**Comment by bcomnes** [comment]
Heads up, the folder scanner function is kinda messed up.

**Comment by ungoldman** [comment]
@bcomnes I'm just experimenting at this point, don't worry about conflicts. I know this will be way off from what you're doing with the footer stuff right now.

Pretty happy with how this is turning out:

screen shot 2017-04-26 at 10 29 21 pm

Mini-player:

screen shot 2017-04-26 at 10 29 26 pm

I made it frameless!

**Comment by ungoldman** [comment]
screen shot 2017-04-26 at 11 40 59 pm

Here's where I ended up ^

Done for tonight. woo

**Comment by bcomnes** [comment]
Looks really good.  Thank you Nate :)

**Comment by bcomnes** [comment]
Merge?

**Comment by ungoldman** [comment]
@bcomnes what about what you're doing with the footer stuff? wouldn't this conflict?

also wanted to rename footer to something more appropriate... maybe even rename player window to main, call footer player, and call the table and search components playlist

**Comment by bcomnes** [comment]
I'll reconcile the two tonight, and then we can rename every thing in one go.

**Comment by obensource** [comment]
@ungoldman looks super nice! Rad!

**Comment by bcomnes** [comment]
Merged with the playback cluster component work.  I'll link the two up later but this is good to merge once tests pass.

**Pull request merged**
