### PR TITLE
add basic config

### LINKED ISSUE #9: Integrate electron-config to persist preferences
Using  https://github.com/sindresorhus/electron-config, lets try to persist preferences to disk.

### PR DESCRIPTION
**Pull request by ungoldman**
> resolves #9 

Hey @bcomnes! I got some basic config working. Also added a few debug tools to make working on the project a little easier. Next step is adding the dialog.

I'm using the default music directory path provided by `app.getPath('music')` for now.

### CODE REVIEW

**Comment by bcomnes** [comment]
Nice work 👍

**Comment by ungoldman** [comment]
@bcomnes I accidentally pushed some stuff to master, sorry 😓

**Comment by ungoldman** [comment]
Got dialog working and made volume control into a real component. I'll just push things to master and close this for now.

**Comment by bcomnes** [comment]
Thats what I was dong this weekend 😊

**Comment by bcomnes** [comment]
Just tried it out.   Looks great!

**Pull request closed without merging**
