### PR TITLE
refactor & restyle

### PR DESCRIPTION
**Pull request by ungoldman**
Working on cleaning up logic here and there, plus experimenting with new styles

screen shot 2017-09-13 at 8 12 06 pm
screen shot 2017-09-13 at 8 12 22 pm

### CODE REVIEW

**Comment by ungoldman** [comment]
more iterations

screen shot 2017-09-13 at 10 50 15 pm
screen shot 2017-09-13 at 10 50 39 pm

really don't like the traffic lights when it's scaled down... 😒

**Comment by ungoldman** [comment]
okay final iteration of the evening. i like the little divider.

screen shot 2017-09-13 at 11 11 46 pm

**Comment by ungoldman** [comment]
ok one more

screen shot 2017-09-13 at 11 16 23 pm
screen shot 2017-09-13 at 11 16 31 pm

**Comment by bcomnes** [comment]
😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻😻

**Comment by ungoldman** [comment]
@bcomnes added keyboard shortcuts

up down left right space ⚡️ ⌨️ ⚡️ 

only caveat is i can't figure out how to call `element.scrollIntoView` on the actual row element that's selected so the viewport follows the selected item as you go down/up

**Pull request merged**
