### PR TITLE
put the * selector back

### PR DESCRIPTION
**Pull request by bcomnes**
I'm going to go ahead and trust you on this one.  I don't have a very good argument the more I think about it.

### CODE REVIEW

**Comment by ungoldman** [comment]
If we're going to do that we might as well do it this updated way:

https://www.paulirish.com/2012/box-sizing-border-box-ftw/

```
/* apply a natural box layout model to all elements, but allowing components to change */
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```

see also https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

**Comment by bcomnes** [comment]
Nice, and it doesn't litter the dom tree with `:before` `:after` elements.

**Comment by ungoldman** [comment]
LGTM

**Comment by ungoldman** [comment]
FYI working on some style stuff for preferences

**Comment by bcomnes** [comment]
Sounds good.  Have you tried doing the sticky table header yet?  I was thinking of doing that next.

**Comment by ungoldman** [comment]
@bcomnes I messed around with it and it didn't seem to work quite right. Almost got there using flexbox instead last night but had to stop because I'm spending too much time on this project this weekend and PJ is getting annoyed.

**Comment by bcomnes** [comment]
Go kick it with PJ!

**Comment by ungoldman** [comment]
Just one more thing...

**Pull request merged**
