### PR TITLE
fix preferences view

### PR DESCRIPTION
**Pull request by ungoldman**
screen shot 2016-12-18 at 2 41 10 pm

Also changed a couple function signatures to have named options so that things are more optional/obvious. Added an optional `children`-style parameter to button to allow for text (or anything else).

### CODE REVIEW

**Comment by bcomnes** [comment]
👍

**Comment by ungoldman** [comment]
Spent a lot of time trying to find a way around the electron / sheet-router reload bug.

**Comment by ungoldman** [comment]
Did choo-location-electron circumvent that issue? You think it would work if we updated it to work with choo v4?

**Comment by bcomnes** [comment]
Pretty annoying when working on preferences I imagine.

**Comment by ungoldman** [comment]
I gotta sign off for now, curious to see how we can get around it.

Yeah, super annoying.

**Comment by bcomnes** [comment]
choo-location-electron did not have a reload after navigation issue in electron.

**Comment by bcomnes** [comment]
Ok I want dis.  Merging.

**Pull request merged**
